config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events do
    resources :participants
    resources :teams do
      get 'participant_teams/new'
      post 'participant_teams/new'
      post 'participant_teams/create'
      resources :points
    end
  end
  # post 'events/pendaftaran'
  get 'events/latest'
  get 'input' , to: 'teams#input'
  root to: 'events#latest'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :participant
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :event
  belongs_to :team, optional: true
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user! , except: [:index, :show, :latest]
  def index
    @events = Event.all.order(id: :asc)
  end

  # def pendaftaran
  #   @event = Event.find(params[:id])
  #   redirect_to @event, notice: 'Pendaftaran telah dirubah'
  # end

  def latest
      @event = Event.last
  end

  def show
      @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

      if @event.save
        redirect_to new_event_path, notice: 'Event berhasil disimpan'
      else
        render :new
        flash[:warning] = 'Gagal simpan, periksa kembali'
      end
  end

  def edit
  end

  def update
    @event = Event.find(params[:event][:id])
    if @event.is_open
      if @event.update(is_open: false)
        redirect_to @event
      end
    else
      if @event.update(is_open: true)
        redirect_to @event
      end
    end
  end

  def destroy
  end

  private

  def event_params
    params.require(:event).permit(:nama_event, :is_open, :deskripsi, :is_tim)
  end
end

app/controllers/participant_teams_controller.rb
class ParticipantTeamsController < ApplicationController
  before_action :authenticate_user! , except: [:index]
  def index
  end

  def new
    @team = Team.find(params[:team_id])
    @event = Event.find(params[:event_id])
    @participant = Participant.new
    @participant_av = Participant.where(team_id: nil)
  end

  def create
    @part = params[:participant]
    @participant = Participant.find(@part[:id])
    if @participant.update(team_id: @part[:team_id])
      redirect_to event_team_participant_teams_new_path, notice: 'Behasil'
    else
      render :new
      flash[:warning] = 'Gagal update, periksa kembali'
    end

  end

  def random
  end

  private
  def p_params
    params.require(:participant).permit(:team_id)
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  def index
    @event = Event.find(params[:event_id])
    @participant = Participant.where(event_id: @event.id).order(id: :desc)
  end

  def new
    @event = Event.find(params[:event_id])
    @participant = Participant.new
  end

  def create
    @event = Event.find(params[:event_id])
    if @event.is_open
      @participant = Participant.new(participant_params)
      if Participant.where(event_id: params[:participant][:event_id], tele_username: params[:participant][:tele_username]).empty?
        if @participant.save
          redirect_to event_participants_path(@event), notice: 'Peserta berhasil disimpan'
        else
          render :new
          flash[:warning] = 'Gagal simpan, periksa kembali'
        end
      else
        flash[:warning] = 'Username yang diinputkan sudah terdaftar'
        render :new
      end
    else
      flash[:warning] = 'Pendaftaran ditutup'
      redirect_to root_path
    end
  end

  def edit
  end

  def destroy
  end

  def participant_params
    params.require(:participant).permit(:display_name, :tele_username, :event_id)
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_action :authenticate_user! , except: [:index]
  def index
    @event = Event.find(params[:event_id])
    @team = Team.find(params[:team_id])
    @point = Point.where(team_id: @team.id).order(id: :desc)
  end

  def new
    @event = Event.find(params[:event_id])
    @team = Team.find(params[:team_id])
    @point = Point.new
  end

  def create
    @event = Event.find(params[:event_id])
    @team = Team.find(params[:team_id])
    @point = Point.new(point_params)
    if @point.save
      redirect_to event_team_points_path(@event, @team), notice: 'Poin berhasil disimpan'
    else
      render :new
      flash[:warning] = 'Gagal simpan, periksa kembali'
    end
  end

  def edit
  end

  def destroy
  end

  private
  def point_params
    params.require(:point).permit(:nilai, :keterangan, :team_id, :oleh)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :authenticate_user! , except: [:index, :input]
  def index
    @event = Event.find(params[:event_id])
    @team = Team.where(event_id: @event.id).order(id: :asc)
    @participant = Participant.where(event_id: @event.id)
    
    @peserta = Array.new
    @index = 0
    @team.each do |t|
      @p = Point.where(team_id: t.id).sum(:nilai)
      # if @peserta.empty?
        @peserta[@index] = [t, @p]
        @index += 1
      # else
        # @peserta.each_with_index do |pes, i|
        #   if @p > @peserta[i][1]
        #     @psr = @peserta[i]
        #     @peserta[i] = [t, @p]
        #     @p = @psr[1]
        #     @peserta[i+1]=@psr
        #   end
        # end
      # end
      
    end
    
    @peserta = @peserta.sort_by{|p| -p[1]}
  end

  # def participant
  #   @event = Event.find(params[:event_id])
  #   @team = Team.where(event_id: @event.id).order(id: :asc)
  #
  # end
  def input
    @event = Event.find(params[:format])
    @team = Team.where(event_id: @event.id).order(id: :asc)
    @participant = Participant.where(event_id: @event.id)
    
    @peserta = Array.new
    @index = 0
    @team.each do |t|
      @p = Point.where(team_id: t.id).sum(:nilai)
      @peserta[@index] = [t, @p]
      @index += 1
    end
     @peserta = @peserta.sort_by{|p| -p[1]}
  end
  
  def new
    @event = Event.find(params[:event_id])
    @team = Team.new
  end

  def create
    @event = Event.find(params[:event_id])
    @team = Team.new(team_params)

    if @team.save
      redirect_to event_teams_path(@event), notice: 'Tim berhasil disimpan'
    else
      render :new
      flash[:warning] = 'Gagal simpan, periksa kembali'
    end
  end

  def edit
  end

  def destroy
  end

  private
  def team_params
    params.require(:team).permit(:title, :event_id, :deskripsi)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def controller?(*controller)
    controller.include?(params[:controller])
  end

  def action?(*action)
    action.include?(params[:action])
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/participant_teams_helper.rb
module ParticipantTeamsHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/events/_form.html.erb
<hr>
<%= form_for @event, :html => {:class => "form-horizontal form-label-left"} do |f| %>
  <%= render "shared/errors", object: @event %>
  <div class="form-group">
    <%= f.label :nama_event, "Title Event :", class: "control-label col-md-3 col-sm-3 col-xs-12" %>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.text_field :nama_event, { autofocus: :true, class: "form-control select2"} %>
      </div>
  </div>
  <div class="ln_solid"></div>

  <div class="form-group">
    <%= f.label :deskripsi, "Deksripsi :", class: "control-label col-md-3 col-sm-3 col-xs-12" %>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.text_area :deskripsi, {class: "form-control", rows: "3", placeholder:"Deskripsi event..."} %>
      </div>
  </div>
  <div class="ln_solid"></div>

  <div class="form-group">
    <%= f.label :is_open, "Buka Pendaftaran :", class: "control-label col-md-3 col-sm-3 col-xs-12" %>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.check_box :is_open, {} %> Ya
      </div>
  </div>
  <div class="ln_solid"></div>
  
    <div class="form-group">
    <%= f.label :is_tim, "Tim :", class: "control-label col-md-3 col-sm-3 col-xs-12" %>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.check_box :is_tim, {} %> Ya
      </div>
  </div>
  <div class="ln_solid"></div>
  
  <div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
      <%= link_to 'Kembali', @url, class: 'btn btn-danger' %>
      <%= f.submit "Simpan", class: "btn btn-primary pull-right" %>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<% @url = events_path %>
<% @aksi = "List" %>
<% @objek = "Event" %>
<% if flash[:notice] %>
<div class="callout callout-info">
  <p><%= flash[:notice] %></p>
</div>
<% end %>

<% if flash[:warning] %>
<div class="callout callout-danger">
  <p><%= flash[:warning] %></p>
</div>
<% end %>

<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-body table-responsive no-padding">
        <table class="table table-hover">
          <thead>
            <tr>
              <td>#</td>
              <td>Title Event</td>
              <td>Pendaftaran</td>
              <td>Aksi</td>
            </tr>
          </thead>
          <tbody>
            <% nomor = 1 %>
            <% @events.each do |e| %>
            <tr>
              <td><%= nomor %></td>
              <td><%= e.nama_event %></td>
              <td><%= e.is_open == true ? '<span class="label label-primary">Open</span>'.html_safe : '<span class="label label-danger">Closed</span>'.html_safe %></td>
              <td>
                <%= link_to 'Join Event', new_event_participant_path(e), class: 'btn btn-primary' %>
                &emsp;
                <%= link_to 'Info', event_path(e), class: 'btn btn-info' %>
                </td>
            </tr>
            <% nomor+=1 %>
            <% end %>
          </tbody>
        </table>
        </div>
      </div>
    </div>
  </div>

app/views/events/latest.html.erb
<% @url = '' %>
<% @aksi = "Terbaru" %>
<% @objek = "Event" %>
<% if flash[:notice] %>
<div class="callout callout-info">
  <p><%= flash[:notice] %></p>
</div>
<% end %>

<% if flash[:warning] %>
<div class="callout callout-danger">
  <p><%= flash[:warning] %></p>
</div>
<% end %>

<%= link_to 'Input Poin', input_path(@event), class: 'btn btn-primary pull-right' %>
<% if !@event.nil? %>
  <% if @event.is_open %>
  <%= form_for(@event, remote: false, data: { confirm: "Yakin tutup pendaftaran?"}) do |fa| %>
    <%= fa.hidden_field :id, :value => @event.id %>
    <%= fa.submit "Tutup Pendaftaran", class: "btn btn-warning pull-left" %>
  <% end %>
  <% else %>
  <%= form_for(@event, remote: false, data: { confirm: "Yakin buka pendaftaran?"}) do |fa| %>
    <%= fa.hidden_field :id, :value => @event.id %>
    <%= fa.submit "Buka Pendaftaran", class: "btn btn-warning pull-left" %>
  <% end %>
  <% end %>

<hr>
<hr>
<div class="row">
  <div class="col-lg-3 col-xs-6">
    <!-- small box -->
    <div class="small-box bg-aqua">
      <div class="inner">
        
        <h3><%= Participant.where(event_id: @event.id).count %></h3>

        <p>Peserta</p>
      </div>
      <a href="<%= event_participants_path(@event) %>" class="small-box-footer">Lihat <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <!-- ./col -->
  <div class="col-lg-3 col-xs-6">
    <!-- small box -->
    <div class="small-box bg-green">
      <div class="inner">
        <% @ada = false %>
        <% if !Team.where(event_id: @event.id).empty? %>
        <h3><%= Team.where(event_id: @event.id).count %></h3>
        <% @ada = true %>
        <% else %>
        <h3>0</h3>
        <% end %>
        <p>Tim</p>
      </div>
      <% if @ada %>
      <a href="<%= event_teams_path(@event) %>" class="small-box-footer">Lihat <i class="fa fa-arrow-circle-right"></i></a>
      <% else %>
       <a href="#" class="small-box-footer">Lihat <i class="fa fa-arrow-circle-right"></i></a>
      <% end %>
    </div>
  </div>
  <!-- ./col -->
  <div class="col-lg-3 col-xs-6">
    <!-- small box -->
    <div class="small-box bg-yellow">
      <div class="inner">
        
        <% if !Team.where(event_id: @event.id).empty? %>
        <h3><%
        @tinggi = 0
        @tim = nil
        @ada = true
        Team.all.each do |t|
  
          @p = Point.where(team_id: t).sum(:nilai)
          if @p > @tinggi
            @tim = t
            @tinggi = @p
          end
        end
          %>
          <%if !@tim.nil? %>
            <%= @tim.title %>
          <% else %>
          Null
          <% @ada = false %>
          <% end %>
        
        </h3>
        <% else %>
        <h3>Null</h3>
        <% end %>

        <p>Tim Unggul</p>
      </div>
      <% if @ada %>
      <a href="<%= event_team_points_path(@event, @tim) %>" class="small-box-footer">Lihat <i class="fa fa-arrow-circle-right"></i></a>
      <% else %>
       <a href="#" class="small-box-footer">Lihat <i class="fa fa-arrow-circle-right"></i></a>
      <% end %>
    </div>
  </div>
  <!-- ./col -->
  <div class="col-lg-3 col-xs-6">
    <!-- small box -->
    <div class="small-box bg-red">
      <div class="inner">
        <h3>Null</h3>
        <p>Peserta Unggul</p>
      </div>
      <% if @ada %>
      <a href="#>" class="small-box-footer">Lihat <i class="fa fa-arrow-circle-right"></i></a>
      <% else %>
       <a href="#" class="small-box-footer">Lihat <i class="fa fa-arrow-circle-right"></i></a>
      <% end %>
    </div>
  </div>
</div> 
<div class="row">
  <div class="col-md-12">
    <div class="box box-solid">
      <div class="box-header with-border">
        <i class="fa fa-text-width"></i>

        <h3 class="box-title">Info Event</h3>
      </div>
      <!-- /.box-header -->
      <div class="box-body">
        <dl class="dl-horizontal">
          <dt>Nama Event</dt>
          <dd><%= @event.nama_event %></dd>
          <dt>Deskripsi</dt>
          <dd>
            <%= simple_format(@event.deskripsi) %>
          </dd>
        </dl>
        <hr>
      <%= link_to 'Lihat Peserta', event_participants_path(@event), class: 'btn btn-primary pull-left' %>
      <%= link_to 'Lihat Tim', event_teams_path(@event), class: 'btn btn-primary pull-right' %>
      </div>
    </div>
  </div>
</div>
<% else %>

<div class="callout callout-danger">
  <p>Tidak ada event terbaru.</p>
</div>
<% end %>

app/views/events/new.html.erb
<% @url = '' %>
<% @aksi = "Tambah" %>
<% @objek = "Event" %>
<% if flash[:notice] %>
<div class="callout callout-info">
  <p><%= flash[:notice] %></p>
</div>
<% end %>

<% if flash[:warning] %>
<div class="callout callout-danger">
  <p><%= flash[:warning] %></p>
</div>
<% end %>
<%= render 'form' %>

app/views/events/show.html.erb
<% @url = '' %>
<% @aksi = "List" %>
<% @objek = "Event" %>
<% if flash[:notice] %>
<div class="callout callout-info">
  <p><%= flash[:notice] %></p>
</div>
<% end %>

<% if flash[:warning] %>
<div class="callout callout-danger">
  <p><%= flash[:warning] %></p>
</div>
<% end %>
<%= link_to 'Tambah Event', new_event_path, class: 'btn btn-primary pull-right' %>
<% if !@event.nil? %>
  <% if @event.is_open %>
  <%= form_for(@event, remote: false, data: { confirm: "Yakin tutup pendaftaran?"}) do |fa| %>
    <%= fa.hidden_field :id, :value => @event.id %>
    <%= fa.submit "Tutup Pendaftaran", class: "btn btn-warning pull-left" %>
  <% end %>
  <% else %>
  <%= form_for(@event, remote: false, data: { confirm: "Yakin buka pendaftaran?"}) do |fa| %>
    <%= fa.hidden_field :id, :value => @event.id %>
    <%= fa.submit "Buka Pendaftaran", class: "btn btn-warning pull-left" %>
  <% end %>
  <% end %>

<hr>
<hr>
<div class="row">
  <div class="col-lg-3 col-xs-6">
    <!-- small box -->
    <div class="small-box bg-aqua">
      <div class="inner">
        
        <h3><%= Participant.where(event_id: @event.id).count %></h3>

        <p>Peserta</p>
      </div>
      <a href="<%= event_participants_path(@event) %>" class="small-box-footer">Lihat <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <!-- ./col -->
  <div class="col-lg-3 col-xs-6">
    <!-- small box -->
    <div class="small-box bg-green">
      <div class="inner">
        <% @ada = false %>
        <% if !Team.where(event_id: @event.id).empty? %>
        <h3><%= Team.where(event_id: @event.id).count %></h3>
        <% @ada = true %>
        <% else %>
        <h3>0</h3>
        <% end %>
        <p>Tim</p>
      </div>
      <% if @ada %>
      <a href="<%= event_teams_path(@event) %>" class="small-box-footer">Lihat <i class="fa fa-arrow-circle-right"></i></a>
      <% else %>
       <a href="#" class="small-box-footer">Lihat <i class="fa fa-arrow-circle-right"></i></a>
      <% end %>
    </div>
  </div>
  <!-- ./col -->
  <div class="col-lg-3 col-xs-6">
    <!-- small box -->
    <div class="small-box bg-yellow">
      <div class="inner">
        
        <% if !Team.where(event_id: @event.id).empty? %>
        <h3><%
        @tinggi = 0
        @tim = nil
        @ada = true
        Team.all.each do |t|
  
          @p = Point.where(team_id: t).sum(:nilai)
          if @p > @tinggi
            @tim = t
            @tinggi = @p
          end
        end
          %>
          <%if !@tim.nil? %>
            <%= @tim.title %>
          <% else %>
          Null
          <% @ada = false %>
          <% end %>
        
        </h3>
        <% else %>
        <h3>Null</h3>
        <% end %>

        <p>Tim Unggul</p>
      </div>
      <% if @ada %>
      <a href="<%= event_team_points_path(@event, @tim) %>" class="small-box-footer">Lihat <i class="fa fa-arrow-circle-right"></i></a>
      <% else %>
       <a href="#" class="small-box-footer">Lihat <i class="fa fa-arrow-circle-right"></i></a>
      <% end %>
    </div>
  </div>
  <!-- ./col -->
  <div class="col-lg-3 col-xs-6">
    <!-- small box -->
    <div class="small-box bg-red">
      <div class="inner">
        <h3>Null</h3>
        <p>Peserta Unggul</p>
      </div>
      <% if @ada %>
      <a href="#>" class="small-box-footer">Lihat <i class="fa fa-arrow-circle-right"></i></a>
      <% else %>
       <a href="#" class="small-box-footer">Lihat <i class="fa fa-arrow-circle-right"></i></a>
      <% end %>
    </div>
  </div>
</div> 
<div class="row">
  <div class="col-md-12">
    <div class="box box-solid">
      <div class="box-header with-border">
        <i class="fa fa-text-width"></i>

        <h3 class="box-title">Info Event</h3>
      </div>
      <!-- /.box-header -->
      <div class="box-body">
        <dl class="dl-horizontal">
          <dt>Nama Event</dt>
          <dd><%= @event.nama_event %></dd>
          <dt>Deskripsi</dt>
          <dd>
            <%= simple_format(@event.deskripsi) %>
          </dd>
        </dl>
        <hr>
      <%= link_to 'Lihat Peserta', event_participants_path(@event), class: 'btn btn-primary pull-left' %>
      <%= link_to 'Lihat Tim', event_teams_path(@event), class: 'btn btn-primary pull-right' %>
      </div>
    </div>
  </div>
</div>
<% else %>

<div class="callout callout-danger">
  <p>Tidak ada event terbaru.</p>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="main-footer">
  <div class="container">
    <div class="pull-right hidden-xs">
      <b>Version</b> 1.0.0
    </div>
    <strong>&copy; <%= Time.current.year %>  < > with RoR and litle touch of 💖 by SMW Admins</strong>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="main-header">
  <nav class="navbar navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <%= link_to '<b>Event</b>SMW'.html_safe, root_path, class: 'navbar-brand' %>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
          <i class="fa fa-bars"></i>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
        <ul class="nav navbar-nav">
          <li class = "<%= 'active' if controller?('events') && action?('latest')%>"><%= link_to 'Home', root_path %></li>
          <li class = "<%= 'active' if controller?('events') && action?('index', 'show')%>"><%= link_to 'List Event', events_path %></li>
        </ul>
      </div>
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <li class="dropdown user user-menu">
            <% if user_signed_in? %>
            <%= link_to current_user.email %>
            <% else %>
            <a href="#">Visitor</a>
            <% end %>
          </li>
          <li class="dropdown user user-menu">
            <% if user_signed_in? %>
            <%=  link_to '', destroy_user_session_path, method: :delete, class: "fa fa-sign-out" %>
            <% else %>
            <%=  link_to '', new_user_session_path, class: "fa fa-sign-in" %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/participant_teams/_form.html.erb
<hr>
<%= form_for @participant, url: event_team_participant_teams_create_path, :html => {:class => "form-horizontal form-label-left"} do |f| %>
  <%= render "shared/errors", object: @participant %>
  <div class="form-group">
    <%= f.label :display_name, "Peserta :", class: "control-label col-md-3 col-sm-3 col-xs-12" %>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.collection_select(:id, @participant_av, :id, :tele_username, {}, {:class => "form-control"}) %>
      </div>
  </div>
  <div class="ln_solid"></div>

  <%= f.hidden_field(:team_id, :value => @team.id) %>
  <%= f.hidden_field(:event_id, :value => @event.id) %>
  <div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
      <%= link_to 'Kembali', @url, class: 'btn btn-danger' %>
      <%= f.submit "Simpan", class: "btn btn-primary pull-right" %>
    </div>
  </div>
<% end %>

app/views/participant_teams/new.html.erb
<% @url = event_teams_path(@event) %>
<% @aksi = "Tambah" %>
<% @objek = "Peserta Tim" %>
<% if flash[:notice] %>
<div class="callout callout-info">
  <p><%= flash[:notice] %></p>
</div>
<% end %>

<% if flash[:warning] %>
<div class="callout callout-danger">
  <p><%= flash[:warning] %></p>
</div>
<% end %>
<%= render 'form' %>

app/views/participants/index.html.erb
<% @url = '' %>
<% @aksi = "List" %>
<% @objek = "Peserta" %>

<% if flash[:notice] %>
<div class="callout callout-info">
  <p><%= flash[:notice] %></p>
</div>
<% end %>

<% if flash[:warning] %>
<div class="callout callout-danger">
  <p><%= flash[:warning] %></p>
</div>
<% end %>

<div class="row">
  <div class="col-xs-12">
    <%= link_to 'Kembali', event_path(@event), class: 'btn btn-danger pull-left' %>
    <%= link_to 'Gabung Event', new_event_participant_path(@event), class: 'btn btn-primary pull-right' %> <hr>
    <div class="box">
      <div class="box-body table-responsive no-padding">
        <table class="table table-hover">
          <thead>
            <tr>
              <td>#</td>
              <td>Display Name</td>
              <td>Telegram Username</td>
              <td>Aksi</td>
            </tr>
          </thead>
          <tbody>
            <% nomor = 1 %>
            <% @participant.each do |p| %>
            <tr>
              <td><%= nomor %></td>
              <td><%= p.display_name %></td>
              <td><%= p.tele_username %></td>
              <td>
                <%= link_to 'Delete', '', class: 'btn btn-danger' %>
                </td>
            </tr>
            <% nomor+=1 %>
            <% end %>
          </tbody>
        </table>
        </div>
      </div>
    </div>
  </div>

app/views/participants/new.html.erb
<% @url = event_participants_url(@event) %>
<% @aksi = "Tambah" %>
<% @objek = "Participant" %>
<% if flash[:notice] %>
<div class="callout callout-info">
  <p><%= flash[:notice] %></p>
</div>
<% end %>

<% if flash[:warning] %>
<div class="callout callout-danger">
  <p><%= flash[:warning] %></p>
</div>
<% end %>
<%= render 'form' %>

app/views/points/index.html.erb
<% @url = event_team_points_path(@event, @team) %>
<% @aksi = "Tambah" %>
<% @objek = @team.title + "'s Point" %>

<% if flash[:notice] %>
<div class="callout callout-info">
  <p><%= flash[:notice] %></p>
</div>
<% end %>

<% if flash[:warning] %>
<div class="callout callout-danger">
  <p><%= flash[:warning] %></p>
</div>
<% end %>

<div class="row">
  <div class="col-xs-12">
    <%= link_to 'Kembali', input_path(@event), class: 'btn btn-danger pull-left' %>
    <%= link_to 'Tambah Point', new_event_team_point_path(@event, @team), class: 'btn btn-primary pull-right' %><hr>
    <div class="box">
      <div class="box-body table-responsive no-padding">
        <table class="table table-hover">
          <thead>
            <tr>
              <td>#</td>
              <td>Nilai</td>
              <td>Waktu</td>
              <td>Keterangan</td>
              <td>Ditambahkan Oleh</td>
            </tr>
          </thead>
          <tbody>

            <% nomor = 1 %>
            <% jumlah = 0 %>
            <% @point.each do |p| %>
            <tr>
              <td><%= nomor %></td>
              <td><%= p.nilai %></td>
              <td><%= p.created_at.in_time_zone("Jakarta").strftime("%d/%m/%Y %H:%M:%S") %></td>
              <td><%= p.keterangan %></td>
              <td><%= p.oleh.split("@").first %></td>
            </tr>
            <% nomor+=1 %>
            <% jumlah+=p.nilai %>
            <% end %>
          </tbody>
          <tfoot>
            <tr>
              <td>Jumlah</td>
              <td colspan="4"><%= jumlah %></td>
            </tr>
          </tfoot>
        </table>
        </div>
      </div>
    </div>
  </div>